name: Playwright Tests
on:
  [ workflow_dispatch ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: Install operating system dependencies
              run: npx playwright install-deps
            - name: Run your tests
              run: npm test